### ISSUE TITLE
Support simple directional map as an AOV

### ISSUE THREAD

**Issue by Wangwentao1** [ElaraFX/OpenElara#1]
For this map， use rgba format， the rgb is the direction of the point's main direction. While the a is the percentage of the irradiance of this direction compare to the whole hemisphere

**Comment by elvicliang** [comment]
This feature is resorted to:

- Added trace_lights option to OSL **trace** call.
- Allow getting is_light attribute to OSL **getmessage** call.

**Comment by ElaraFX** [comment]
Fixed in Elara SDK 1.0.65
