### ISSUE TITLE
Automatically disable env_emits_GI when any portal light is created

### ISSUE THREAD

**Issue by ElaraFX** [ElaraFX/OpenElara#27]
- Automatically disable env_emits_GI when any portal light is created.
- env_emits_GI is true by default.

**Comment by WindyPaper** [comment]
@https://github.com/ElaraFX/OpenElara/commit/7a29e4a3a2fc66bf68e0eeaa2d205cc674828b64

**Comment by ElaraFX** [comment]
Looking good.
